-- MySQL Script generated by MySQL Workbench
-- Mon Sep 27 16:11:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema message
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema message
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `message` DEFAULT CHARACTER SET utf8 ;
USE `message` ;

-- -----------------------------------------------------
-- Table `message`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `message`.`message` (
  `name` VARCHAR(25) NOT NULL,
  `idno` INT NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `message` VARCHAR(45) NULL,
  PRIMARY KEY (`idno`),
  UNIQUE INDEX `idno_UNIQUE` (`idno` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
